{ lib, raccoonlib, stdenv, fetchFromGitHub, pcre, openssl ? null
, useOpenSSL ? true }:

assert useOpenSSL -> openssl != null;

stdenv.mkDerivation rec {
  pname = "fuzzball";
  version = "7.0";

  src = fetchFromGitHub {
    owner = "fuzzball-muck";
    repo = "fuzzball";
    rev = "v${version}";
    hash = "sha256-TvgTY+j2556XGwDI5YuQ+mgWAXditGT9wtzFPXpuO78=";
  };

  buildInputs = [ pcre ] ++ lib.optional useOpenSSL openssl;

  configureFlags = [
    "--with-pcre=${pcre.dev}"
  ] ++ lib.optional useOpenSSL "--with-ssl=${openssl.dev}";

  postInstall = ''
    # sbin contains `fb-restart` which is already in the game directory as `restart`
    # this script is written to be modified by the sysadmin, so it shouldn't go in the store
    rm -r $out/sbin

    # include starter db's and gamedir, which are necessary and not auto-generated by `fbmuck`
    # `game/restart` is included as-is, but it has bad default values for nix.
    #   you should use the nixos module anyway
    rm game/restart.in
    cp -r dbs game $out/share/doc/fbmuck
  '';

  meta = with lib;
    with raccoonlib; {
      description = "An online interactive multiplayer chat/role-play MUD server with a persistent database";
      license = licenses.gpl3Only;
      maintainers = [ maintainers.raccoon ];
    };
}
